server {
    # コンテナの８０番ポートでリクエストを受け付ける
    listen 80;

    # Laravelの公開ディレクトリ（起点）
    root /var/www/html/public;
    index index.php index.html;

    location / {
        # try_filesで対応するURLがなければindex.phpを渡す
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # PHPの処理をappコンテナの9000番ポートに渡す（NginxとPHP-FPMの橋渡し）
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}